<template>
  <div id="app">

            <input type="checkbox" checked id="pure-toggle-left" class="pure-toggle" data-toggle="left"/>
            <label class="pure-toggle-label" for="pure-toggle-left" data-toggle-label="left"><span class="pure-toggle-icon"></span></label>


            <nav class="pure-drawer" data-position="left">
                <div id="left-panel" >
                      <ul class="nav">
                        <li v-for="link in links" @click="OpenURL(link.url)"> {{ link.text }}   </li>
                      </ul>
                    <div class="left-nav">
                          <ul class="nav">
                            <li v-for="company in dsecompanies" :class="{active:selectedCompany == company.script}">  

                              <h5  @click="ShowChart(company.script)" > {{ company.script }}  </h5>
                              <small  @click="ShowChart(company.script)" >{{ company.title }} </small>

                              <span> 
                                <i class="fa fa-bar-chart"  @click="ShowChart(company.script)"  ></i> 
                                <i class="fa fa-line-chart"  @click="ShowCompanyDetails(company.script, company.stockId)"  ></i> 
                                <i class="fa fa-newspaper-o "  @click="showCompanyStatistic(company.script, company.stockId)"  ></i> 

                                <i class="fa fa-picture-o"  @click="ShowSBCompanyDetails(company.script)"  ></i> 



                              </span>
                            </li>
                          </ul>
                    </div>
              </div>
            </nav>   
            
            <div class="pure-pusher-container">
                <div class="pure-pusher">
                    <div style="width: 100%; height: 100%; margin: 100px auto;">
                       <iframe v-if="iframeURL" :src="iframeURL"  > </iframe >
                    </div>
                </div>
            </div>

            <label class="pure-overlay" for="pure-toggle-left" data-overlay="left"></label> 

  </div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return { 
        iframeURL: 'http://lankabd.com/portal/DSE/smartChartFullScreen.html?symbol=DSEX&siteLanguage=en', 
        selectedCompany: '',
        links: [
                {
                  text: "Data Matrix2",
                  url: 'http://www.stockbangladesh.com/grids/data_matrix2'
                },
                {
                  text: "SmartChart",
                  url: 'http://lankabd.com/portal/DSE/smartChartFullScreen.html?symbol=DSEX&siteLanguage=en'
                },
                {
                  text: "TodayNews",
                  url: 'http://lankabd.com/news'
                },
                {
                  text: "StockCompare",
                  url: 'http://www.stockbangladesh.com/symbols/comparewith/22647/0'
                },
                {
                  text: "MarketFrame",
                  url: 'http://www.stockbangladesh.com/financials/market_frame'
                },
                {
                  text: "Arthosuchak",
                  url: 'http://www.arthosuchak.com/'
                } 
               ],

     unshortdsecompanies: [{script:'PROGRESLIF', title:'Progressive Life Insurance Co. Limited', stockId: 220 },
        {script:'SAVAREFR', title:'Savar Refractories Limited', stockId: 127 },
        {script:'SUNLIFEINS', title:'Sunlife Insurance Company Limited', stockId: 301 },
        {script:'RSRMSTEEL', title:'Ratanpur Steel Re-Rolling Mills Limited', stockId: 620 },
        {script:'HRTEX', title:'H.R.Textile Mills Limited', stockId: 171 },
        {script:'ATLASBANG', title:'Atlas Bangladesh Limited', stockId: 44 },
        {script:'LANKABAFIN', title:'LankaBangla Finance Limited', stockId: 76 },
        {script:'KAY&QUE', title:'Kay and Que Bangladesh Limited', stockId: 53 },
        {script:'SAIFPOWER', title:'Saif Powertec Limited', stockId: 621 },
        {script:'CONTININS', title:'Continental Insurance Limited', stockId: 194 },
        {script:'RAHIMTEXT', title:'Rahim Textile Mills Limited', stockId: 178 },
        {script:'NHFIL', title:'National Housing Finance and Investment Limited', stockId: 78 },
        {script:'IDLC', title:'IDLC Finance Limited', stockId: 72 },
        {script:'MEGHNACEM', title:'Meghna Cement Mills Limited', stockId: 6 },
        {script:'REPUBLIC', title:'Republic Insurance Company Limited', stockId: 224 },
        {script:'CONFIDCEM', title:'Confidence Cement Limited', stockId: 3 },
        {script:'KPPL', title:'Khulna Printing & Packaging Limited', stockId: 614 },
        {script:'RANFOUNDRY', title:'Rangpur Foundry Limited', stockId: 61 },
        {script:'IFADAUTOS', title:'IFAD Autos Limited', stockId: 627 },
        {script:'ALARABANK', title:'Al-Arafah Islami Bank Limited', stockId: 13 },
        {script:'SHYAMPSUG', title:'Shyampur Sugar Mills Limited', stockId: 99 },
        {script:'BANGAS', title:'Bangas Limited', stockId: 88 },
        {script:'KDSALTD', title:'KDS Accessories Limited', stockId: 636 },
        {script:'UTTARAFIN', title:'Uttara Finance Limited', stockId: 85 },
        {script:'SONALIANSH', title:'Sonali Aansh Industries Limited', stockId: 120 },
        {script:'BENGALWTL', title:'Bengal Windsor Thermoplastics Limited', stockId: 561 },
        {script:'GSPFINANCE', title:'GSP Finance Company (Bangladesh) Limited ', stockId: 287 },
        {script:'NTLTUBES', title:'National Tubes Limited', stockId: 58 },
        {script:'FASFIN', title:'FAS Finance & Investment Limited', stockId: 69 },
        {script:'CENTRALINS', title:'Central Insurance Company Ltd.', stockId: 192 },
        {script:'PHOENIXFIN', title:'Phoenix Finance and Investments Limited', stockId: 79 },
        {script:'BSCCL', title:'Bangladesh Submarine Cable Company Limited  ', stockId: 279 },
        {script:'ZAHINTEX', title:'Zahintex Industries Limited', stockId: 273 },
        {script:'GHAIL', title:'Golden Harvest Agro Industries Limited', stockId: 303 },
        {script:'PADMALIFE', title:'Padma Islami Life Insurance Limited ', stockId: 288 },
        {script:'OAL', title:'Olympic Accessories Limited', stockId: 634 },
        {script:'FAREASTFIN', title:'Fareast Finance & Investment Limited', stockId: 582 },
        {script:'CVOPRL', title:'CVO PETROCHEMICAL REFINERY LIMITED', stockId: 275 },
        {script:'NLI1STMF', title:'NLI FIRST MUTUAL FUND', stockId: 293 },
        {script:'UNITEDFIN', title:'United Finance Limited', stockId: 83 },
        {script:'KEYACOSMET', title:'Keya Cosmetics Limited', stockId: 141 },
        {script:'CITYGENINS', title:'City General Insurance Company Limited', stockId: 193 },
        {script:'JANATAINS', title:'Janata Insurance Company Ltd.', stockId: 204 },
        {script:'PDL', title:'Pacific Denims Limited', stockId: 652 },
        {script:'SONARBAINS', title:'Sonar Bangla Insurance Limited', stockId: 228 },
        {script:'EXIM1STMF', title:'EXIM Bank 1st Mutual Fund', stockId: 566 },
        {script:'DHAKAINS', title:'Dhaka Insurance Limited', stockId: 196 },
        {script:'PRIMEINSUR', title:'Prime Insurance Company Limited', stockId: 218 },
        {script:'IFILISLMF1', title:'IFIL Islamic Mutual Fund-1', stockId: 263 },
        {script:'MBL1STMF', title:'MBL 1st Mutual Fund', stockId: 264 },
        {script:'AIBL1STIMF', title:'AIBL 1st Islamic Mutual Fund', stockId: 247 },
        {script:'ISLAMICFIN', title:'Islamic Finance & Investment Limited', stockId: 75 },
        {script:'PREMIERLEA', title:'Premier Leasing & Finance Limited', stockId: 81 },
        {script:'DSSL', title:'Dragon Sweater and Spinning Limited', stockId: 642 },
        {script:'REGENTTEX', title:'Regent Textile Mills Limited', stockId: 638 },
        {script:'BIFC', title:'Bangladesh Industrial Fin. Company Limited', stockId: 67 },
        {script:'ARGONDENIM', title:'Argon Denims Limited', stockId: 298 },
        {script:'TALLUSPIN', title:'Tallu Spinning Spinning Mills Limited', stockId: 185 },
        {script:'CAPMBDBLMF', title:'CAPM BDBL Mutual Fund 01', stockId: 651 },
        {script:'ETL', title:'Evince Textiles Limited', stockId: 646 },
        {script:'JMISMDL', title:'JMI Syringes & Medical Devices Ltd', stockId: 565 },
        {script:'MONNOSTAF', title:'Monno Jute Stafflers Limited', stockId: 55 },
        {script:'BDAUTOCA', title:'Bangladesh Autocars Limited', stockId: 46 },
        {script:'PRIMELIFE', title:'Prime Islami Life Insurance Limited', stockId: 219 },
        {script:'YPL', title:'Yeakin Polymer Limited', stockId: 647 },
        {script:'KARNAPHULI', title:'Karnaphuli Insurance Company Ltd.', stockId: 205 },
        {script:'ICB', title:'Investment Corporation of Bangladesh', stockId: 71 },
        {script:'JUTESPINN', title:'Jute Spinners Limited', stockId: 118 },
        {script:'JAMUNABANK', title:'Jamuna Bank Limited', stockId: 25 },
        {script:'HWAWELLTEX', title:'Hwa Well Textiles (BD) Limited', stockId: 608 },
        {script:'SONARGAON', title:'Sonargaon Textiles Limited', stockId: 182 },
        {script:'ITC', title:'Information Technology Consultants Limited', stockId: 639 },
        {script:'MICEMENT', title:'M.I. Cement Factory Limited', stockId: 7 },
        {script:'SEBL1STMF', title:'Southeast Bank 1st Mutual Fund', stockId: 269 },
        {script:'FUWANGCER', title:'Fu-Wang Ceramic Limited', stockId: 8 },
        {script:'GOLDENSON', title:'Golden Son Limited', stockId: 52 },
        {script:'LINDEBD', title:'Linde Bangladesh Limited', stockId: 289 },
        {script:'BAYLEASING', title:'Bay Leasing & Investment Limited', stockId: 65 },
        {script:'AFTABAUTO', title:'Aftab Automobiles Limited', stockId: 42 },
        {script:'PHARMAID', title:'Pharma Aids Limited', stockId: 146 },
        {script:'INTECH', title:'Intech Limited', stockId: 116 },
        {script:'ICB3RDNRB', title:'ICB AMCL Third NRB Mutual Fund', stockId: 257 },
        {script:'KPCL', title:'Khulna Power Company Limited', stockId: 107 },
        {script:'IPDC', title:'IPDC Finance Limited', stockId: 74 },
        {script:'FEKDIL', title:'Far East Knitting & Dyeing Industries Limited', stockId: 611 },
        {script:'ICBEPMF1S1', title:'ICB Employees Provident MF 1: Scheme 1', stockId: 260 },
        {script:'MODERNDYE', title:'Modern Dyeing & Screen Printing Limited', stockId: 176 },
        {script:'LRGLOBMF1', title:'LR Global Bangladesh Mutual Fund One', stockId: 232 },
        {script:'NAVANACNG', title:'Navana CNG Limited', stockId: 56 },
        {script:'ABBANK', title:'AB Bank Limited', stockId: 1 },
        {script:'RAKCERAMIC', title:'RAK Ceramics (Bangladesh) Limited', stockId: 10 },
        {script:'ECABLES', title:'Eastern Cables Limited', stockId: 51 },
        {script:'SHAHJABANK', title:'Shahjalal Islami Bank Limited', stockId: 35 },
        {script:'IFIC', title:'IFIC Bank Limited', stockId: 23 },
        {script:'HFL', title:'Hamid Fabrics Limited', stockId: 624 },
        {script:'GREENDELMF', title:'Green Delta Mutual Fund', stockId: 254 },
        {script:'UNIONCAP', title:'Union Capital Limited', stockId: 84 },
        {script:'DBH1STMF', title:'DBH First Mutual Fund', stockId: 249 },
        {script:'TRUSTBANK', title:'Trust Bank Limited', stockId: 39 },
        {script:'BBS', title:'Bangladesh Building System Ltd.', stockId: 585 },
        {script:'BDFINANCE', title:'Bangladesh Finance and Investment Company Limited', stockId: 66 },
        {script:'BXPHARMA', title:'BEXIMCO Pharma ', stockId: 136 },
        {script:'MAKSONSPIN', title:'Maksons Spinning Mills Limited', stockId: 172 },
        {script:'MALEKSPIN', title:'Malek Spinning Mills Limited', stockId: 173 },
        {script:'NORTHRNINS', title:'Northern General Insurance Co. Ltd.', stockId: 210 },
        {script:'GLOBALINS', title:'Global Insurance Ltd.', stockId: 201 },
        {script:'RAHIMAFOOD', title:'Rahima Food Limited', stockId: 98 },
        {script:'DBH', title:'Delta Brac Housing Finance Corp. Limited', stockId: 68 },
        {script:'ICB2NDNRB', title:'ICB AMCL 2nd NRB Mutual Fund', stockId: 256 },
        {script:'DHAKABANK', title:'Dhaka Bank Limited', stockId: 17 },
        {script:'KBPPWBIL', title:'Khan Brothers PP Woven Bag Industries Ltd.', stockId: 623 },
        {script:'MIRACLEIND', title:'Miracle Industries Limited', stockId: 126 },
        {script:'DSHGARME', title:'Desh Garmants Limited', stockId: 169 },
        {script:'BNICL', title:'Bangladesh National Insurance Company Limited', stockId: 645 },
        {script:'PRAGATIINS', title:'Pragati Insurance Limited', stockId: 216 },
        {script:'PHENIXINS', title:'Phoenix Insurance Company Ltd.', stockId: 213 },
        {script:'SHURWID', title:'Shurwid Industries Limited', stockId: 619 },
        {script:'EBL', title:'Eastern Bank Limited', stockId: 19 },
        {script:'AGNISYSL', title:'Agni Systems Limited', stockId: 113 },
        {script:'SPCERAMICS', title:'Shinepukur Ceramics Limited', stockId: 11 },
        {script:'PRIMEFIN', title:'Prime Finance & Investment Limited', stockId: 82 },
        {script:'BEACHHATCH', title:'Beach Hatchery Limited', stockId: 90 },
        {script:'UCB', title:'United Commercial Bank Limited', stockId: 40 },
        {script:'BSC', title:'Bangladesh Shipping Corporation', stockId: 124 },
        {script:'ZAHEENSPIN', title:'Zaheen Spinning Limited', stockId: 629 },
        {script:'FARCHEM', title:'Far Chemicals Industries Limited', stockId: 612 },
        {script:'AMBEEPHA', title:'Ambee Pharmaceuticals Limited', stockId: 134 },
        {script:'MHSML', title:'Mozaffar Hossain Spinning Mills Limited', stockId: 599 },
        {script:'NPOLYMAR', title:'National Polymer Industries Limited', stockId: 57 },
        {script:'DESHBANDHU', title:'Deshbandhu Polymer Limited', stockId: 50 },
        {script:'FEDERALINS', title:'Federal Insurance Company Limited', stockId: 200 },
        {script:'NBL', title:'National Bank Limited', stockId: 28 },
        {script:'SQURPHARMA', title:'Square Pharmaceuticals Limited', stockId: 150 },
        {script:'EXIMBANK', title:'Export Import (Exim) Bank of Bangladesh', stockId: 20 },
        {script:'NCCBANK', title:'NCC Bank Limited', stockId: 29 },
        {script:'HEIDELBCEM', title:'Heidelberg Cement Bangladesh Limited', stockId: 4 },
        {script:'DUTCHBANGL', title:'Dutch-Bangla Bank Limited', stockId: 18 },
        {script:'MJLBD', title:'MJL Bangladesh Limited', stockId: 272 },
        {script:'STYLECRAFT', title:'Stylecraft Limited', stockId: 184 },
        {script:'PIONEERINS', title:'Pioneer Insurance Comapny Limited', stockId: 214 },
        {script:'MPETROLEUM', title:'Meghna Petroleum Limited', stockId: 108 },
        {script:'MERCANBANK', title:'Mercantile Bank Limited', stockId: 26 },
        {script:'FORTUNE', title:'Fortune Shoes Limited', stockId: 648 },
        {script:'BANKASIA', title:'Bank Asia Limited', stockId: 14 },
        {script:'ONEBANKLTD', title:'One Bank Limited', stockId: 30 },
        {script:'BGIC', title:'Bangladesh General Insurance Company Ltd. ', stockId: 191 },
        {script:'GHCL', title:'Global Heavy Chemicals Limited', stockId: 304 },
        {script:'UPGDCL', title:'United Power Generation & Distribution Company Limited', stockId: 631 },
        {script:'KOHINOOR', title:'Kohinoor Chemicals Limited', stockId: 142 },
        {script:'DOREENPWR', title:'Doreen Power Generations and Systems Limited', stockId: 643 },
        {script:'BDLAMPS', title:'Bangladesh Lamps Limited', stockId: 47 },
        {script:'BARKAPOWER', title:'Baraka Power Limited', stockId: 102 },
        {script:'SINGERBD', title:'Singer Bangladesh Limited', stockId: 64 },
        {script:'LEGACYFOOT', title:'Legacy Footwear Limited', stockId: 158 },
        {script:'BERGERPBL', title:'Berger Paints Bangladesh Limited', stockId: 122 },
        {script:'AMANFEED', title:'Aman Feed Limited', stockId: 635 },
        {script:'IBBLPBOND', title:'IBBL Mudaraba Perpetual Bond', stockId: 235 },
        {script:'NITOLINS', title:'Nitol Insurance Company Limited', stockId: 209 },
        {script:'UTTARABANK', title:'Uttara Bank Limited', stockId: 41 },
        {script:'NTC', title:'National Tea Company Limited', stockId: 97 },
        {script:'MITHUNKNIT', title:'Mithun Knitting and Dyeing Limited', stockId: 175 },
        {script:'BATASHOE', title:'Bata Shoe Limited', stockId: 157 },
        {script:'EMERALDOIL', title:'Emerald Oil Industries Limited', stockId: 604 },
        {script:'EASTERNINS', title:'Eastern Insurance Company Ltd.', stockId: 197 },
        {script:'BSRMLTD', title:'Bangladesh Steel Re-Rolling Mills Limited', stockId: 632 },
        {script:'SQUARETEXT', title:'Square Textile Limited', stockId: 183 },
        {script:'DELTALIFE', title:'Delta Life Insurance Limited', stockId: 195 },
        {script:'OLYMPIC', title:'Olympic Industries', stockId: 59 },
        {script:'RECKITTBEN', title:'Reckitt Benckiser(Bd.)Limited', stockId: 147 },
        {script:'GPHISPAT', title:'GPH Ispat Limited', stockId: 286 },
        {script:'RUPALILIFE', title:'Rupali Life Insurance Company Limited', stockId: 226 },
        {script:'EHL', title:'Eastern Housing Limited', stockId: 151 },
        {script:'IBNSINA', title:'The Ibn Sina Pharmaceutical Industry Limited', stockId: 139 },
        {script:'TITASGAS', title:'Titas Gas Transmission & Distribution Company Limited', stockId: 112 },
        {script:'BSRMSTEEL', title:'BSRM Steels Limited', stockId: 49 },
        {script:'ORIONPHARM', title:'Orion Pharma Limited', stockId: 325 },
        {script:'ACI', title:'ACI Limited', stockId: 131 },
        {script:'BRACBANK', title:'BRAC Bank Limited', stockId: 15 },
        {script:'APEXTANRY', title:'Apex Tannery Limited', stockId: 156 },
        {script:'FAREASTLIF', title:'Fareast Islami Life Insurance Company Limited', stockId: 199 },
        {script:'PADMAOIL', title:'Padma Oil Company Limited', stockId: 109 },
        {script:'ILFSL', title:'International Leasing & Financial Services Limited', stockId: 73 },
        {script:'ORIONINFU', title:'Orion Infusion Limited', stockId: 145 },
        {script:'SOUTHEASTB', title:'Southeast Bank Limited', stockId: 37 },
        {script:'LAFSURCEML', title:'Lafarge Surma Cement Limited', stockId: 5 },
        {script:'MIDASFIN', title:'MIDAS Financing Limited', stockId: 77 },
        {script:'PROVATIINS', title:'Provati Insurance Company Limited', stockId: 221 },
        {script:'PLFSL', title:'Peoples Leasing and Financial Services Limited', stockId: 80 },
        {script:'POPULAR1MF', title:'Popular Life First Mutual Fund', stockId: 267 },
        {script:'1JANATAMF', title:'First Janata Bank Mutual Fund', stockId: 236 },
        {script:'EBL1STMF', title:'EBL First Mutual Fund', stockId: 250 },
        {script:'PHPMF1', title:'PHP First Mutual Fund', stockId: 266 },
        {script:'ENVOYTEX', title:'Envoy Textiles Limited', stockId: 299 }, 
        {script:'RUPALIINS', title:'Rupali Insurance Company Limited', stockId: 225 },
        {script:'PREMIERBAN', title:'The Premier Bank Limited', stockId: 31 },
        {script:'SAMATALETH', title:'Samata Leather Complex Limited', stockId: 159 },
        {script:'ABB1STMF', title:'AB BANK 1ST MUTUAL FUND', stockId: 294 },
        {script:'SAIHAMCOT', title:'Saiham Cotton Mills Limited', stockId: 290 },
        {script:'NATLIFEINS', title:'National Life Insurance Company Limited', stockId: 208 },
        {script:'SEMLLECMF', title:'SEML Lecture Equity Management Fund', stockId: 640 },
        {script:'BDWELDING', title:'Bangladesh Welding Electrodes Limited', stockId: 101 },
        {script:'RDFOOD', title:'Rangpur Dairy & Food Products Limited', stockId: 274 },
        {script:'ICBIBANK', title:'ICB Islamic Bank Limited', stockId: 22 },
        {script:'NCCBLMF1', title:'NCCBL MUTUAL FUND-1', stockId: 292 },
        {script:'ISNLTD', title:'Information Services Network Limited', stockId: 117 },
        {script:'TOSRIFA', title:'Tosrifa Industries Limited', stockId: 633 },
        {script:'ICBSONALI1', title:'ICB AMCL Sonali Bank Limited 1st Mutual Fund', stockId: 563 },
        {script:'GENNEXT', title:'Generation Next Fashions Limited', stockId: 300 },
        {script:'STANDBANKL', title:'Standard Bank Limited', stockId: 38 },
        {script:'FIRSTSBANK', title:'First Security Islami Bank Limited', stockId: 21 },
        {script:'RELIANCE1', title:'Reliance One the 1st scheme of Reliance Insurance Mutual Fund', stockId: 271 },
        {script:'IFIC1STMF', title:'IFIC Bank 1st Mutual Fund', stockId: 262 },
        {script:'TRUSTB1MF', title:'Trust Bank 1st Mutual Fund', stockId: 270 },
        {script:'FIRSTFIN', title:'First Finance Limited', stockId: 70 },
        {script:'DACCADYE', title:'The Dacca Dyeing & Manufacturing Co.Limited', stockId: 167 },
        {script:'UNITEDAIR', title:'United Airways (BD) Limited', stockId: 187 },
        {script:'GP', title:'Grameenphone Limited', stockId: 160 },
        {script:'RENWICKJA', title:'Renwick Jajneswar & Company (Bd)', stockId: 62 },
        {script:'BATBC', title:'British American Tobacco Bangladesh Company', stockId: 89 },
        {script:'WATACHEM', title:'Wata Chemicals Ltd', stockId: 609 },
        {script:'RENATA', title:'Renata Limited', stockId: 148 },
        {script:'USMANIAGL', title:'Usmania Glass Sheet Factory Limited', stockId: 129 },
        {script:'PREMIERCEM', title:'Premier Cement Mills Limited', stockId: 302 },
        {script:'ACTIVEFINE', title:'Active Fine Chemicals Limited', stockId: 133 },
        {script:'MATINSPINN', title:'Matin Spinning Mills Limited', stockId: 606 },
        {script:'QSMDRYCELL', title:'Quasem Drycells Limited', stockId: 60 },
        {script:'UNIQUEHRL', title:'Unique Hotel & Resorts Limited', stockId: 296 },
        {script:'RELIANCINS', title:'Reliance Insurance Limited', stockId: 223 },
        {script:'GEMINISEA', title:'Gemini Sea Food Limited', stockId: 94 },
        {script:'EASTLAND', title:'Eastland Insurance Company Limited', stockId: 198 },
        {script:'ICB1STNRB', title:'ICB AMCL 1st NRB Mutual Fund', stockId: 255 },
        {script:'APOLOISPAT', title:'Appollo Ispat Complex Limited', stockId: 597 },
        {script:'GBBPOWER', title:'GBB Power Limited', stockId: 284 },
        {script:'ARAMIT', title:'Aramit Limited', stockId: 121 },
        {script:'SAPORTL', title:'Summit Alliance Port Limited', stockId: 154 },
        {script:'MERCINS', title:'Mercantile Insurance Company Ltd.', stockId: 207 },
        {script:'ACIFORMULA', title:'ACI Formulations Limited', stockId: 132 },
        {script:'PARAMOUNT', title:'Paramount Insurance Co. Ltd.', stockId: 211 },
        {script:'APEXSPINN', title:'Apex Spinning & Knitting Mills Limited', stockId: 164 },
        {script:'SALAMCRST', title:'S. Alam Cold Rolled Steels Limited', stockId: 63 },
        {script:'POWERGRID', title:'Power Grid Company of Bangladesh Limited', stockId: 110 },
        {script:'MARICO', title:'Marico Bangladesh Limited', stockId: 144 },
        {script:'AAMRATECH', title:'Aamra Technologies Limited', stockId: 297 },
        {script:'SHASHADNIM', title:'Shasha Denims Limited', stockId: 628 },
        {script:'BEXIMCO', title:'BEXIMCO Limited', stockId: 123 },
        {script:'SPCL', title:'Shahjibazar Power Co. Ltd.', stockId: 613 },
        {script:'SAMORITA', title:'Samorita Hospital Limited', stockId: 153 },
        {script:'UNITEDINS', title:'United Insurance Company Ltd.', stockId: 231 },
        {script:'SAFKOSPINN', title:'Safko Spinnings Mills Limited', stockId: 180 },
        {script:'TUNGHAI', title:'Tung Hai Knitting & Dyeing Limited', stockId: 617 },
        {script:'MONNOCERA', title:'Monno Ceramic Industries Limited', stockId: 9 },
        {script:'SIMTEX', title:'Simtex Industries Ltd.', stockId: 637 },
        {script:'AFCAGRO', title:'AFC Agro Biotech Limited', stockId: 602 },
        {script:'AMCL(PRAN)', title:'Agricultural Marketing Co Ltd.', stockId: 86 },
        {script:'HAKKANIPUL', title:'Hakkani Pulp & Paper Mills Limited', stockId: 130 },
        {script:'PUBALIBANK', title:'Pubali Bank Limited', stockId: 33 },
        {script:'ALLTEX', title:'Alltex Industries Limited', stockId: 162 },
        {script:'SANDHANINS', title:'Sandhani Life Insurance', stockId: 227 },
        {script:'PTL', title:'Paramount Textile Limited', stockId: 587 },
        {script:'BEACONPHAR', title:'Beacon Pharmaceuticals Limited', stockId: 135 },
        {script:'POPULARLIF', title:'Popular Life Insurance Co. Limited', stockId: 215 },
        {script:'DELTASPINN', title:'Delta Spinners Limited', stockId: 168 },
        {script:'GLAXOSMITH', title:'Glaxo SmithKline PLC', stockId: 138 },
        {script:'ATCSLGF', title:'Asian Tiger Sandhani Life Growth Fund', stockId: 630 },
        {script:'JAMUNAOIL', title:'Jamuna Oil Company Limited', stockId: 106 },
        {script:'RUPALIBANK', title:'Rupali Bank Limited', stockId: 34 },
        {script:'NFML', title:'National Feed Mill Limited', stockId: 625 },
        {script:'APEXFOOT', title:'Apex Footwear Limited', stockId: 155 },
        {script:'MEGHNAPET', title:'Meghna Pet Industries Limited', stockId: 96 },
        {script:'TAKAFULINS', title:'Takaful Islami Insurance Limited', stockId: 230 },
        {script:'CENTRALPHL', title:'Central Pharmaceuticals Limited', stockId: 567 },
        {script:'PRIMEBANK', title:'Prime Bank Limited', stockId: 32 },
        {script:'RNSPIN', title:'R.N. Spinning Mills Limited', stockId: 179 },
        {script:'FAMILYTEX', title:'Familytex (BD) Limited', stockId: 564 },
        {script:'SAIHAMTEX', title:'Saiham Textile Mills Limited', stockId: 181 },
        {script:'STANDARINS', title:'Standard Insurance Limited', stockId: 229 },
        {script:'VAMLRBBF', title:'Vanguard AML Rupali Bank Balanced Fund', stockId: 649 },
        {script:'BXSYNTH', title:'Beximco Synthetics Limited', stockId: 137 },
        {script:'LIBRAINFU', title:'Libra Infusions Limited', stockId: 143 },
        {script:'FINEFOODS', title:'Fine Foods Limited', stockId: 92 },
        {script:'ICBAMCL2ND', title:'ICB AMCL Second Mutual Fund', stockId: 259 },
        {script:'SUMITPOWER', title:'Summit Power Limited', stockId: 111 },
        {script:'EASTRNLUB', title:'Eastern Lubricants Blenders Limited', stockId: 105 },
        {script:'PEOPLESINS', title:'Peoples Insurance Company Limited', stockId: 212 },
        {script:'DESCO', title:'Dhaka Electric Supply Company Limited', stockId: 104 },
        {script:'PRAGATILIF', title:'Pragati Life Insurance Limited', stockId: 217 },
        {script:'METROSPIN', title:'Metro Spinning Limited', stockId: 174 },
        {script:'EBLNRBMF', title:'EBL NRB Mutual Fund', stockId: 251 },
        {script:'FUWANGFOOD', title:'Fu Wang Foods Limited', stockId: 93 },
        {script:'PF1STMF', title:'Phoenix Finance 1st Mutual Fund', stockId: 265 },
        {script:'BDTHAI', title:'Bangladesh Thai Aluminium Limited', stockId: 48 },
        {script:'WMSHIPYARD', title:'Western Marine Shipyard Limited', stockId: 622 },
        {script:'GRAMEENS2', title:'Grameen One : Scheme Two', stockId: 253 },
        {script:'PRIME1ICBA', title:'Prime Bank 1st ICB AMCL Mutual Fund', stockId: 268 },
        {script:'ACMELAB', title:'The ACME Laboratories Limited ', stockId: 644 },
        {script:'SIBL', title:'Social Islami Bank Limited', stockId: 36 },
        {script:'ASIAINS', title:'Asia Insurance Limited', stockId: 189 },
        {script:'FBFIF', title:'First Bangladesh Fixed Income Fund', stockId: 291 },
        {script:'CITYBANK', title:'The City Bank Limited', stockId: 16 },
        {script:'1STPRIMFMF', title:'Prime Finance First Mutual Fund', stockId: 239 },
        {script:'DAFODILCOM', title:'Daffodil Computers Limited', stockId: 115 },
        {script:'BDCOM', title:'BDCOM Online Limited', stockId: 114 },
        {script:'MEGHNALIFE', title:'Meghna Life Insurance Company Limited', stockId: 206 },
        {script:'ISLAMIBANK', title:'Islami Bank Limited', stockId: 24 },
        {script:'ANWARGALV', title:'Anwar Galvanizing Limited', stockId: 43 },
        {script:'PURABIGEN', title:'Purabi General Insurance Co. Ltd.', stockId: 222 },
        {script:'SALVOCHEM', title:'Salvo Chemical Industry Limited', stockId: 149 },
        {script:'APEXFOODS', title:'Apex Foods Limited', stockId: 87 },
        {script:'CNATEX', title:'C & A Textiles Limited', stockId: 626 },
        {script:'PRIMETEX', title:'Prime Textile Spinning Mills Limited', stockId: 177 },
        {script:'MEGCONMILK', title:'Meghna Condensed Milk Industries Limited', stockId: 95 },
        {script:'NORTHERN', title:'Northern Jute Manufacturing Company Limited', stockId: 119 },
        {script:'CMCKAMAL', title:'CMC Kamal Textile Mills Limited', stockId: 166 },
        {script:'AZIZPIPES', title:'Aziz Pipes Limited', stockId: 45 },
        {script:'PENINSULA', title:'The Peninsula Chittagong Limited', stockId: 610 },
        {script:'DULAMIACOT', title:'Dulamia Cotton Spinning Mills Limited', stockId: 170 },
        {script:'ASIAPACINS', title:'Asia Pacific General Insurance Company Limited', stockId: 190 },
        {script:'AGRANINS', title:'Agrani Insurance Company Ltd.', stockId: 188 },
        {script:'STANCERAM', title:'Standard Ceramic Limited', stockId: 12 },
        {script:'ARAMITCEM', title:'Aramit Cement', stockId: 2 },
        {script:'ISLAMIINS', title:'Islami Insurance Bangladesh Limited', stockId: 203 },
        {script:'SINOBANGLA', title:'Sinobangla Industries Limited', stockId: 128 },
        {script:'GQBALLPEN', title:'GQ Ball Pen Industries Limited', stockId: 125 },
        {script:'IMAMBUTTON', title:'Imam Button Industries Limited', stockId: 140 },
        {script:'MTB', title:'Mutual Trust Bank Ltd.', stockId: 27 },
        {script:'ANLIMAYARN', title:'Anlima Yarn Dyeing Limited', stockId: 163 },
        {script:'GREENDELT', title:'Green Delta Insurance Company Limited', stockId: 202 },
        {script:'ZEALBANGLA', title:'Zeal Bangla Sugar Mills Limited', stockId: 100 }],

        stockbangladesh:  {
SB1JANATAMF : '12178' ,
SB1STBSRS : '12160' ,
SB1STICB : '12152' ,
SB1STPRIMFMF : '12168' ,
SB2NDICB : '12153' ,
SB3RDICB : '12154' ,
SB4THICB : '12155' ,
SB5THICB : '12156' ,
SB6THICB : '12157' ,
SB7THICB : '12158' ,
SB8THICB : '12159' ,
SBAAMRATECH : '22647' ,
SBABB1STMF : '12189' ,
SBABBANK : '11101' ,
SBACI : '18455' ,
SBACIFORMULA : '18480' ,
SBACIZCBOND : '26002' ,
SBACMELAB : '18491' ,
SBACTIVEFINE : '18483' ,
SBAFCAGRO : '18489' ,
SBAFTABAUTO : '13201' ,
SBAGNISYSL : '22645' ,
SBAGRANINS : '25722' ,
SBAIBL1STIMF : '12183' ,
SBAIMS1STMF : '12161' , 
SBALAMINCHEM : '18478' ,
SBALARABANK : '11115' ,
SBALLTEX : '17440' ,
SBALPHATOBA : '14252' ,
SBAMAMSEAFD : '14253' ,
SBAMANFEED : '99641' ,
SBAMBEEPHA : '18451' , 
SBANLIMAYARN : '17441' ,
SBANWARGALV : '13221' ,
SBAPEXFOODS : '14254' ,
SBAPEXFOOT : '23619' ,
SBAPEXSPINN : '17421' ,
SBAPEXTANRY : '23601' ,
SBAPEXWEAV : '17428' ,
SBAPOLOISPAT : '13233' ,
SBARAMIT : '99602' ,
SBARAMITCEM : '21633' ,
SBARGONDENIM : '17456' ,
SBASHRAFTEX : '17402' ,
SBASIAINS : '25740' ,
SBASIAPACINS : '25729' ,
SBATCSLGF : '12195' ,
SBATLASBANG : '13212' ,
SBAZIZPIPES : '13202' ,
SBBANGAS : '14257' ,
SBBANGLAPRO : '18452' ,
SBBANKASIA : '11127' ,
SBBARKAPOWER : '15313' ,
SBBATASHOE : '23603' ,
SBBATBC : '14259' ,
SBBAYLEASING : '11148' ,
SBBBS : '13232' ,
SBBCIL : '18466' ,
SBBDAUTOCA : '13213' ,
SBBDCOM : '22643' ,
SBBDDYE : '17426' ,
SBBDFINANCE : '11142' ,
SBBDHOTELS  : '20551' ,
SBBDLAMPS : '13204' ,
SBBDLUGGAGE : '99625' ,
SBBDONLINE : '22639' ,
SBBDPLANT : '14271' ,
SBBDSERVICE : '20552' ,
SBBDTHAI : '13219' ,
SBBDWELDING : '15305' ,
SBBDZIPPER : '17432' ,
SBBEACHHATCH : '14291' ,
SBBEACONPHAR : '18482' ,
SBBEMCO : '13220' ,
SBBENGALBISC : '14274' ,
SBBENGALFINE : '24624' ,
SBBENGALWTL : '13231' ,
SBBERGERPBL : '99638' ,
SBBEXIMCO : '99613' ,
SBBEXTEX : '17420' ,
SBBGIC : '25701' ,
SBBIFC : '11136' ,
SBBIONICFOOD : '14285' ,
SBBLTC : '14258' ,
SBBNICL : '25747' ,
SBBRACBANK : '11138' ,
SBBRACSCBOND : '26003' ,
SBBSC : '99604' ,
SBBSCCL : '27002' ,
SBBSRMLTD : '13238' ,
SBBSRMSTEEL : '13227' ,
SBBXFISHERY : '14273' ,
SBBXPHARMA : '18453' ,
SBBXSYNTH : '18470' ,
SBCAPMBDBLMF : '12199' ,
SBCENTRALINS : '25709' ,
SBCENTRALPHL : '18488' ,
SBCHICTEX : '17437' ,
SBCITYBANK : '11102' ,
SBCITYGENINS : '25734' ,
SBCMCKAMAL : '17444' ,
SBCNATEX : '17465' ,
SBCONFIDCEM : '21621' ,
SBCONTININS : '25735' ,
SBCVOPRL : '14269' ,
SBDACCADYE : '17449' ,
SBDAFODILCOM : '22646' ,
SBDANDYDYE : '17429' ,
SBDBH : '20621' ,
SBDBH1STMF : '12174' ,
SBDEBBXDENIM : '17433' ,
SBDEBBXKNI : '17422' ,
SBDELTALIFE : '25716' ,
SBDELTASPINN : '17427' ,
SBDESCO : '15307' ,
SBDESHBANDHU : '13229' ,
SBDHAKABANK : '11118' ,
SBDHAKAFISH : '14278' ,
SBDHAKAINS : '25744' ,
SBDOREENPWR : '15319' ,
SBDSEGEN : '1' ,
SBDSES : '6' ,
SBDSEX : '5' ,
SBDSHGARME : '17415' ,
SBDSSL : '17471' ,
SBDULAMIACOT : '17416' ,
SBDUTCHBANGL : '11121' ,
SBDYNAMICTEX : '17423' ,
SBEAGLESTAR : '17414' ,
SBEASTERNINS : '25705' ,
SBEASTLAND : '25708' ,
SBEASTRNLUB : '15303' ,
SBEBL : '11112' ,
SBEBL1STMF : '12169' ,
SBEBLNRBMF : '12186' ,
SBECABLES : '13206' ,
SBEHL : '20620' ,
SBEMERALDOIL : '14295' ,
SBENGINEER : '99609' ,
SBENVOYTEX : '17455' ,
SBETL : '17472' ,
SBEXCELSHOE : '23627' ,
SBEXIM1STMF : '12194' ,
SBEXIMBANK : '11129' ,
SBFAMILYTEX : '17457' ,
SBFARCHEM : '18490' ,
SBFAREASTFIN : '28023' ,
SBFAREASTLIF : '25725' ,
SBFASFIN : '11146' ,
SBFBFIF : '12191' ,
SBFEDERALINS : '25713' ,
SBFEKDIL : '17462' ,
SBFINEFOODS : '14292' ,
SBFIRSTFIN : '11124' ,
SBFIRSTSBANK : '11147' ,
SBFORTUNE : '23637' ,
SBFUWANGCER : '24632' ,
SBFUWANGFOOD : '14286' ,
SBGACHIHATA : '14284' ,
SBGBBPOWER : '15315' ,
SBGBJVFOOD : '14289' ,
SBGEMINISEA : '14262' ,
SBGENNEXT : '17454' ,
SBGHAIL : '14294' ,
SBGHCL : '18485' ,
SBGLAXOSMITH : '18454' ,
SBGLOBALINS : '25723' ,
SBGMGIND : '17405' ,
SBGOLDENSON : '13226' ,
SBGP : '27001' ,
SBGPHISPAT : '13230' ,
SBGQBALLPEN : '99605' ,
SBGRAMEEN1 : '12164' ,
SBGRAMEENS2 : '12167' ,
SBGREENDELMF : '12179' ,
SBGREENDELT : '25702' ,
SBGSPFINANCE : '11149' ,
SBGULFOODS : '14282' ,
SBHAKKANIPUL : '19510' ,
SBHEIDELBCEM : '21614' ,
SBHFL : '17464' ,
SBHILLPLANT : '14272' ,
SBHIMADRI : '99615' ,
SBHRTEX : '17442' ,
SBHWAWELLTEX : '17461' ,
SBIBBLPBOND : '26001' ,
SBIBNSINA : '18464' ,
SBICB : '12151' ,
SBICB1STNRB : '12165' ,
SBICB2NDNRB : '12166' ,
SBICB3RDNRB : '12177' ,
SBICBAMCL1ST : '12162' ,
SBICBAMCL2ND : '12170' ,
SBICBEPMF1S1 : '12171' ,
SBICBIBANK : '11110' ,
SBICBISLAMIC : '12163' ,
SBICBSONALI1 : '12193' ,
SBIDLC : '11111' ,
SBIFADAUTOS : '13237' ,
SBIFIC : '11103' ,
SBIFIC1STMF : '12175' ,
SBIFILISLMF1 : '12181' ,
SBILFSL : '11143' ,
SBIMAMBUTTON : '18474' ,
SBINTECH : '22644' ,
SBIPDC : '11137' ,
SBISLAMIBANK : '11104' ,
SBISLAMICFIN : '11133' ,
SBISLAMIINS : '25742' ,
SBISNLTD : '22641' ,
SBITC : '22648' ,
SBJAMUNABANK : '11134' ,
SBJAMUNAOIL : '15309' ,
SBJANATAINS : '25706' ,
SBJMISMDL : '18487' ,
SBJUTESPINN : '16355' ,
SBKARNAPHULI : '25710' ,
SBKBPPWBIL : '99639' ,
SBKDSALTD : '13240' ,
SBKEYACOSMET : '18477' ,
SBKEYADETERG : '18479' ,
SBKOHINOOR : '18463' ,
SBKPCL : '15312' ,
SBKPPL : '19511' ,
SBLAFSURCEML : '21643' ,
SBLANKABAFIN : '11135' ,
SBLEGACYFOOT : '23636' ,
SBLEXCO : '23623' ,
SBLIBRAINFU : '18471' ,
SBLINDEBD : '15301' ,
SBLRGLOBMF1 : '12188' ,
SBMAKSONSPIN : '17448' ,
SBMALEKSPIN : '17451' ,
SBMAQENTER : '19509' ,
SBMAQPAPER : '19508' ,
SBMARICO : '18481' ,
SBMATINSPINN : '17460' ,
SBMBL1STMF : '12184' ,
SBMEGCONMILK : '14290' ,
SBMEGHNACEM : '21622' ,
SBMEGHNALIFE : '25726' ,
SBMEGHNAPET : '14287' ,
SBMEGHNASHRM : '14275' ,
SBMERCANBANK : '11128' ,
SBMERCINS : '25721' ,
SBMETROSPIN : '17447' ,
SBMHOSSAIN : '17435' ,
SBMHSML : '17459' ,
SBMICEMENT : '21644' ,
SBMIDASFIN : '11122' ,
SBMIRACLEIND : '99637' ,
SBMITATEX : '17425' ,
SBMITHUNKNIT : '17424' ,
SBMJLBD : '15314' ,
SBMODERNCEM : '21640' ,
SBMODERNDYE : '17413' ,
SBMODERNIND : '14610' ,
SBMONAFOOD : '14283' ,
SBMONNOCERA : '24606' ,
SBMONNOFABR : '17439' ,
SBMONNOJTX : '13208' ,
SBMONNOSTAF : '13209' ,
SBMONOSPOOL : '19505' ,
SBMPETROLEUM : '15310' ,
SBMTB : '11123' ,
SBNATLIFEINS : '25712' ,
SBNAVANACNG : '13228' ,
SBNBL : '11105' ,
SBNCCBANK : '11119' ,
SBNCCBLMF1 : '12192' ,
SBNFML : '99640' ,
SBNHFIL : '20623' ,
SBNILOYCEM : '21630' ,
SBNITOLINS : '25727' ,
SBNLI1STMF : '12190' ,
SBNORTHERN : '16357' ,
SBNORTHRNINS : '25738' ,
SBNPOLYMAR : '18469' ,
SBNTC : '14263' ,
SBNTLTUBES : '13218' ,
SBOAL : '13239' ,
SBOCL : '20624' ,
SBOLYMPIC : '13203' ,
SBONEBANKLTD : '11126' ,
SBORIONINFU : '18472' ,
SBORIONPHARM : '18486' ,
SBPADMACEM : '21642' ,
SBPADMALIFE : '25745' ,
SBPADMAOIL : '15302' ,
SBPADMAPRINT : '19501' ,
SBPAPERPROC : '19506' ,
SBPARAMOUNT : '25733' ,
SBPDL : '17473' ,
SBPENINSULA : '29003' ,
SBPEOPLESINS : '25704' ,
SBPERFUMCHM : '18475' ,
SBPETROSYNTH : '18456' ,
SBPF1STMF : '12176' ,
SBPHARMACO : '18458' ,
SBPHARMAID : '18462' ,
SBPHENIXINS : '25707' ,
SBPHOENIXFIN : '11144' ,
SBPHPMF1 : '12182' ,
SBPIONEERINS : '25720' ,
SBPLFSL : '11130' ,
SBPOPULAR1MF : '12180' ,
SBPOPULARLIF : '25724' ,
SBPOWERGRID : '15308' ,
SBPRAGATIINS : '25717' ,
SBPRAGATILIF : '25731' ,
SBPREMIERBAN : '11140' ,
SBPREMIERCEM : '21645' ,
SBPREMIERLEA : '11132' ,
SBPRIME1ICBA : '12173' ,
SBPRIMEBANK : '11116' ,
SBPRIMEFIN : '11131' ,
SBPRIMEINSUR : '25719' ,
SBPRIMELIFE : '25732' ,
SBPRIMETEX : '17434' ,
SBPROGRESLIF : '25728' ,
SBPROVATIINS : '25743' ,
SBPTL : '17458' ,
SBPUBALIBANK : '11106' ,
SBPURABIGEN : '25715' ,
SBQSMDRYCELL : '13214' ,
SBQSMSILK : '17411' ,
SBQSMTEX : '17406' ,
SBRAHIMAFOOD : '14281' ,
SBRAHIMTEXT : '17410' ,
SBRAHMANCHEM : '18465' ,
SBRAKCERAMIC : '24634' ,
SBRANFOUNDRY : '13224' ,
SBRANGAFOOD : '14288' ,
SBRASPIT : '14276' ,
SBRASPITDATA : '22638' ,
SBRDFOOD : '14293' ,
SBRECKITTBEN : '18460' ,
SBREGENTTEX : '17470' ,
SBRELIANCE1 : '12187' ,
SBRELIANCINS : '25714' ,
SBRENATA : '18457' ,
SBRENWICKJA : '13215' ,
SBREPUBLIC : '25739' ,
SBRNSPIN : '17450' ,
SBROSEHEAVEN : '99631' ,
SBRSRMSTEEL : '13235' ,
SBRUPALIBANK : '11107' ,
SBRUPALIINS : '25711' ,
SBRUPALILIFE : '25741' ,
SBSAFKOSPINN : '17445' ,
SBSAIFPOWER : '20625' ,
SBSAIHAMCOT : '17453' ,
SBSAIHAMTEX : '17412' ,
SBSAJIBKNIT : '17436' ,
SBSALAMCRST : '13225' ,
SBSALEHCARPT : '16363' ,
SBSALVOCHEM : '18484' ,
SBSAMATALETH : '23634' ,
SBSAMORITA : '20553' ,
SBSANDHANINS : '25718' ,
SBSAPORTL : '20622' ,
SBSAVAREFR : '99611' ,
SBSB71 : '4' ,
SBSEBL1STMF : '12185' ,
SBSEMLLECMF : '12196' ,
SBSHAHJABANK : '11139' ,
SBSHASHADNIM : '17466' ,
SBSHINEPUKUR : '20359' ,
SBSHURWID : '13234' ,
SBSHYAMPSUG : '14279' ,
SBSIBL : '11120' ,
SBSIMTEX : '17469' ,
SBSINGERBD : '13211' ,
SBSINOBANGLA : '99635' ,
SBSONALIANSH : '16360' ,
SBSONALIPAPR : '19503' ,
SBSONARBAINS : '25730' ,
SBSONARGAON : '17430' ,
SBSOUTHEASTB : '11117' ,
SBSPCERAMICS : '24633' ,
SBSPCL : '15317' ,
SBSPPCL : '15316' ,
SBSQUARETEXT : '17446' ,
SBSQURPHARMA : '18473' ,
SBSREEPURTEX : '17438' ,
SBSTANCERAM : '24626' ,
SBSTANDARINS : '25737' ,
SBSTANDBANKL : '11125' ,
SBSTYLECRAFT : '17408' ,
SBSUMITPOWER : '15306' ,
SBSUNLIFEINS : '25746' ,
SBTAKAFULINS : '25736' ,
SBTALLUSPIN : '17417' ,
SBTAMIJTEX : '17419' ,
SBTBL : '18461' ,
SBTITASGAS : '15311' ,
SBTOSRIFA : '17468' ,
SBTRIPTI : '14256' ,
SBTRUSTB1MF : '12172' ,
SBTRUSTBANK : '11145' ,
SBTULIPDAIRY : '14268' ,
SBTUNGHAI : '17463' ,
SBUCB : '11108' ,
SBUNIONCAP : '11141' ,
SBUNIQUEHRL : '29002' ,
SBUNITEDAIR : '29001' ,
SBUNITEDFIN : '11113' ,
SBUNITEDINS : '25703' ,
SBUPGDCL : '15318' ,
SBUSMANIAGL : '99608' ,
SBUTTARABANK : '11109' ,
SBUTTARAFIN : '11114' ,
SBVAMLBDMF1 : '12197' ,
SBVAMLRBBF : '12198' ,
SBWATACHEM : '18467' ,
SBWMSHIPYARD : '13236' ,
SBWONDERTOYS : '13223' ,
SBYOUSUFLOUR : '14264' ,
SBYPL : '13241' ,
SBZAHEENSPIN : '17467' ,
SBZAHINTEX : '17452' ,
SBZEALBANGLA : '14266'  } 
        
    }

    },
    computed: {
      dsecompanies: function () {
        return _.orderBy(this.unshortdsecompanies, 'script')
      }
    },
   mounted(){ 
        //var _this = this;
        //console.log(this.stockbangladesh);

        // axios.get('/companies.json')
        // .then(function (response) { 
        //     _this.dsecompanies = response.data ;
        // })
        // .catch(function (error) {
        //   console.log(error);
        // });
  },
  methods:{
     OpenURL: function(url){ 
          this.iframeURL = url; 

     },
     ShowChart: function(script){
           this.selectedCompany = script;
           this.iframeURL =  'http://lankabd.com/portal/DSE/smartChartFullScreen.html?symbol='+script+'&siteLanguage=en';
     },
     ShowSBCompanyDetails: function(script){
           this.selectedCompany = script;
           this.iframeURL =  'http://www.stockbangladesh.com/symbols/details2/'+ this.stockbangladesh['SB'+script]+'/0';
 
     },
     ShowCompanyDetails: function(script, stockId){
           this.selectedCompany = script;
           this.iframeURL =  'http://lankabd.com/dse/stock-market/'+script+'/progressive-life-insurance-co.-limited/stock-price?stockId='+ stockId;
     },
     showCompanyStatistic: function(script, stockId){
           this.selectedCompany = script;
           this.iframeURL =  'http://lankabd.com/dse/stock-market/'+script+'POWERGRID/power-grid-company-of-bangladesh-limited/Statistics-Dividend-shareholding-pattern?companyId='+stockId+'&stockId='+ stockId;
     }
  }
}
</script>

<style> 
#left-panel{ margin-top: 100px;}
.left-nav{ max-height: 90%; overflow: auto;  height: 400px;  }

iframe { width: 90%; height: 100%; border: none; min-height: 900px;}
ul.nav, 
ul.nav li{ list-style:none; margin: 2px 0; padding: 5px 10px; width: 90%;   cursor: pointer;  }
ul.nav li{  color: #fff; border-bottom: 1px dotted #777;  text-align: left; }
ul.nav li.active, ul.nav li:hover{ background: #000;}
ul.nav li i{  color: #fff; cursor: pointer; margin-right: 10px; cursor: pointer; }
ul.nav li span{display: block; margin-top: 5px; } 

h5 { margin: 0 ; padding:2px 0;}

::-webkit-scrollbar {
    width: 12px;
}
::-webkit-scrollbar-track {
    background-color: #eaeaea;
    border-left: 1px solid #ccc;
}
::-webkit-scrollbar-thumb {
    background-color: #ccc;
}
::-webkit-scrollbar-thumb:hover {
  background-color: #aaa;
}

</style>
